### ISSUE TITLE
Appeal

### ISSUE THREAD

**Issue by 82852** [lukasexists/muenster-appeals#1]
###### To get your token, open Muenster, and once you've reached the ban screen, click "Get Token for Appeals"
token here

## What do you believe you were banned for?
I said the n word

## Did you do it, and if so, what are your thoughts on your past actions?
I did say the n word because I was testing the profanity filter. It wasn't working, so I was going to contact you. I'm really sorry.

**Comment by ToasterPanic** [comment]
i totally forgot that muenster existed for the most part an i am so sorry

for future reference, let us test it instead so this doesnt happen

approved, you'll be unbanned shortly

**Comment by 82852** [comment]
thanks.
